#!/usr/bin/env bash
# Test using associative array to simplify calls and to improve readability.

parse_pwrstat() {
  mapfile -t parsed_value < <(pwrstat -status | awk -F '[.]+' '
    /Model Name/        { print $2 }
    /State/             { print $2 }
    /Battery Capacity/  { print $2 }
    /Remaining Runtime/ { print $2 }
    /Load/              { print $2 }
    /Last Power Event/  { print $2 }
  ')

}
parse_pwrstat

echo "Model Name:       ${parsed_value[0]}"
echo "Status:           ${parsed_value[1]}"
echo "Battery Capacity: ${parsed_value[2]}"
echo "Remaining Runtime:${parsed_value[3]}"
echo "Load:             ${parsed_value[4]}"
echo "Last Power Event: ${parsed_value[5]}"
