#!/usr/bin/env bash
# Test using associative array to simplify calls and to improve readability.

parse_pwrstat() {
  mapfile -t parsed_value < <(pwrstat -status | awk -F '[.]+' '
    /Model Name/        { print $2 }
    /State/             { print $2 }
    /Battery Capacity/  { print $2 }
    /Remaining Runtime/ { print $2 }
    /Load/              { print $2 }
    /Last Power Event/  { print $2 }
  ')
}
parse_pwrstat

printf "%s\n" "Model Name:       ${parsed_value[0]}"
printf "%s\n" "Status:           ${parsed_value[1]}"
printf "%s\n" "Battery Capacity: ${parsed_value[2]}"
printf "%s\n" "Remaining Runtime:${parsed_value[3]}"
printf "%s\n" "Load:             ${parsed_value[4]}"
printf "%s\n" "Last Power Event: ${parsed_value[5]}"
