#!/usr/bin/env bash

# Check if command (e.g.'pwrstat')--provided as an argument--exists on host.
# Exit if not.
command_check() {
  for cmd in "$@"; do
    command -v "$cmd" >/dev/null 2>&1 ||
      { printf "%s\n" >&2 "'$cmd' not detected. Exiting."; exit 1; }
  done
}

command_check "pwrstat"
