#!/usr/bin/env bash
# Check if command(s)--provided as argument(s)--exists.
# Exit if command not found.

command_check() {
  for cmd in "$@"; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
      printf "%s\n" "Error: Required command "$cmd" not found. Exiting." >&2
      exit 1
    fi
done
}

command_check "pwrstat" "whiptail"
