#!/usr/bin/env bash
# Check if data file exists, Exit if not.

script=$(basename "$0")
program="power_UPS"

data_file="upps_data.csv"

data_file_check() {
  if [ ! -f "$data_file" ]; then
    whiptail --backtitle "$script" --title "$program" --msgbox "Data file '$data_file' not found. Exiting." 10 40 0
    exit 1
  fi
}

data_file_check
