#!/usr/bin/env bash
# Parse output of `pwrstat`

script=$(basename "$0")
program="power_UPS"

# Create associative array ('parsed_values') via redirection
# awk splits the output of each line of the 'pwrstat -status' command
# wherever it finds one or more periods ('.').
parse_pwrstat() {
  mapfile -t parsed_values < <(pwrstat -status | awk -F '[.]+' '
    /Model Name/        { print $2 }
    /Firmware Number/   { print $2 }
    /State/             { print $2 }
    /Power Supply by/   { print $2 }
    /Battery Capacity/  { print $2 }
    /Remaining Runtime/ { print $2 }
    /Load/              { print $2 }
    /Last Power Event/  { print $2 }
  ')
}

parse_pwrstat

format_parsed_values() {
  printf "Model Name:       %s\n" "${parsed_values[0]}"
  printf "Firmware Number:  %s\n" "${parsed_values[1]}"
  printf "State:            %s\n" "${parsed_values[2]}"
  printf "Power Supply by:  %s\n" "${parsed_values[3]}"
  printf "Battery Capacity: %s\n" "${parsed_values[4]}"
# printf "Remaining Runtime:%s\n" "${parsed_values[5]}"
# printf "Load:             %s\n" "${parsed_values[6]}"
  printf "Last Power Event: %s\n" "${parsed_values[7]}"
}

ups_stats() {
  local formatted_output
  formatted_output=$(format_parsed_values)
  TERM=ansi whiptail --backtitle "$script" --title "$program" --msgbox "$formatted_output" 16 72 0
}

ups_stats
