#!/usr/bin/env bash
# Parse output of `pwrstat` command and print.

# Create associative array ('parsed_values') via redirection
# awk splits the output of each line of the 'pwrstat -status' command
# wherever it finds one or more periods ('.').
parse_pwrstat_text_only() {
  mapfile -t parsed_values < <(pwrstat -status | awk -F '[.]+' '
    /Model Name/        { print $2 }
    /State/             { print $2 }
    /Battery Capacity/  { print $2 }
    /Remaining Runtime/ { print $2 }
    /Load/              { print $2 }
    /Last Power Event/  { print $2 }
  ')
}

parse_pwrstat_text_only

# Print output cleanly.
printf "%s\n" "Model Name:       ${parsed_values[0]}"
printf "%s\n" "Status:           ${parsed_values[1]}"
printf "%s\n" "Battery Capacity: ${parsed_values[2]}"
printf "%s\n" "Remaining Runtime:${parsed_values[3]}"
printf "%s\n" "Load:             ${parsed_values[4]}"
printf "%s\n" "Last Power Event: ${parsed_values[5]}"
