#!/usr/bin/env bash
# Generate faux progress bar while UPS self-test runs

# Run pwrstat test silently
run_test() {
  pwrstat -test >/dev/null 2>&1
}

{ # Create subshell and pipe progress values to whiptail
  # Run the UPS test in the background
  run_test & 
  test_pid=$!

  # Simulate a 15-second progress bar
  for ((i = 0; i <= 150; i++)); do
    sleep 0.1
    printf "%s\n" $((i * 100 / 150))
  done

  # Wait for the UPS test to complete
  wait $test_pid
} | whiptail --gauge "Running the UPS test. Please wait..." 6 50 0

# Print pwrstat status
pwrstat -status
