#!/bin/bash

run_test() {
 
    pwrstat -test >/dev/null 2>&1
}

{   # Use a subshell to group the commands and pipe the progress values to whiptail
    # Run the UPS test in the background
    run_test & 
    test_pid=$!

    # Simulate a 15-second progress bar
    for ((i = 0; i <= 150; i++)); do
        sleep 0.1
        echo $((i * 100 / 150))
    done

    # Wait for the UPS test to complete
    wait $test_pid
} | whiptail --gauge "Running the UPS test. Please wait..." 6 50 0

pwrstat -status
