#!/usr/local/bin bash
# Set parameters for pwrstat pwrfail option.

script=$(basename "$0")
program="power_UPS"

pwrstat -pwrfail [-delay <seconds>] [-active on | off] [-cmd <shell_script>] [-duration <seconds>] [-shutdown on | off]
