#!/usr/bin/env bash
# Parse ups_data.csv and create formatted table:
# UPS Load(Watts)  Minutes of Runtime(estimated)
# ---------------  -----------------------------

script=$(basename "$0")
program="PowerUPS"

TABLE=$(awk -F ',' '{ printf "%-15s %-30s\n", $1, $2}' ups_data.csv)

estimated_runtimes() {
  TERM=ansi whiptail --backtitle "$script" --title "$program" --msgbox "$TABLE" 30 54
}

main() {
  estimated_runtimes
}

main "$@"
