#!/usr/bin/env bash
# Parse ups_data.csv and create formatted table:
# UPS Load(Watts)  Minutes of Runtime(estimated)
# ---------------  -----------------------------
# 50               229
# 100              137
# 200              65.7

script=$(basename "$0")
program="PowerUPS"
data_file="ups_data.csv"

# TABLE=$(awk -F ',' '{ printf "%-15s %-30s\n", $1, $2}' "$data_file")

ups_runtime() {
  local table
  table=$(awk -F ',' '{ printf "%-15s %-30s\n", $1, $2}' "$data_file")

  TERM=ansi whiptail --backtitle "$script" --title "$program" --msgbox "$table" 30 54
}

ups_runtime
