#!/usr/bin/env bash

command -v pwrstat >/dev/null 2>&1 || { printf "%s\n" >&2 "'pwrstat' not detected. Exiting."; exit 1; }

script=$(basename "$0")
program="PowerUPS"

TEST=$(pwrstat -test >/dev/null 2>&1 && sleep 1)
RESULT=$(pwrstat -status | awk -F '[.]+' '/Test Result/ {print "Test Result:", "            ",$2}')

upsTest() {
  TERM=ansi whiptail --backtitle "$script" --title "$program" --msgbox "$RESULT" 12 72
}

main() {
  upsTest
}

main "$@"
