#!/usr/bin/env bash

command -v pwrstat >/dev/null 2>&1 || { printf "%s\n" >&2 "'pwrstat' not detected. Exiting."; exit 1; }

script=$(basename "$0")
program="PowerUPS"

MODEL=$(pwrstat -status |awk -F '[.]+' '/Model Name/ {print "Model Name:", "      ", $2}')
EVENT=$(pwrstat -status |awk -F '[.]+' '/Power Event/ {print "Status:", "          ",$2}')
BATTERY=$(pwrstat -status |awk -F '[.]+' '/Battery Capacity/ {print "Battery Capacity:", "",$2}')
RUNTIME=$(pwrstat -status |awk -F '[.]+' '/Remaining Runtime/ {print "Remaining Runtime:", $2}')
LOAD=$(pwrstat -status |awk -F '[.]+' '/Load/ {print "Load:", "            ",$2}')

upsStats() {
  whiptail --backtitle "$script" --title "$program" --msgbox "
  $MODEL
  $EVENT
  $BATTERY
  $RUNTIME
  $LOAD
  " 12 72
}

main() {
  upsStats
}

main "$@"
